// <auto-generated />
using System;
using Financas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financas.Migrations
{
    [DbContext(typeof(MoneyContext))]
    [Migration("20230223002036_UpdateDespesa")]
    partial class UpdateDespesa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Finanças.Models.Conta", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Saldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Login");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("Finanças.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContaLogin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataCobranca")
                        .HasColumnType("DATE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QntdParcelas")
                        .HasColumnType("int");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ContaLogin");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("Finanças.Models.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContaLogin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<bool>("Realizada")
                        .HasColumnType("bit");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ContaLogin");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("Finanças.Models.Transação", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContaLogin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("DATE");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ContaLogin");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("Finanças.Models.Despesa", b =>
                {
                    b.HasOne("Finanças.Models.Conta", null)
                        .WithMany("Despesas")
                        .HasForeignKey("ContaLogin");
                });

            modelBuilder.Entity("Finanças.Models.Meta", b =>
                {
                    b.HasOne("Finanças.Models.Conta", null)
                        .WithMany("Metas")
                        .HasForeignKey("ContaLogin");
                });

            modelBuilder.Entity("Finanças.Models.Transação", b =>
                {
                    b.HasOne("Finanças.Models.Conta", null)
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaLogin");
                });

            modelBuilder.Entity("Finanças.Models.Conta", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Metas");

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
